eureka:
  client:
    serviceUrl:
      defaultZone: http://hello:12344444/eureka/
      zone1: http://zone1:55/eureka/
      zone2: http://zone2:88/eureka/
    availabilityZones:
      region2: zone1,zone2
    region: region2
    
